### ISSUE TITLE
It seems I am unable to install new plugins.

### ISSUE THREAD

**Issue by jtw023** [ChristianChiarulli/LunarVim#277]
It's likely a noob mistake as I'm unfamiliar with packer as a plugin manager. There are two specific plugins that I was hoping to install:
1. [norcalli/nvim-colorizer.lua](https://github.com/norcalli/nvim-colorizer.lua)
2. [vimwiki/vimwiki](https://github.com/vimwiki/vimwiki)

What I have done so far:
~~~
yay -S neovim-git
rm -rf .config/nvim/
bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
git clone https://github.com/norcalli/nvim-colorizer.lua.git ~/.local/share/nvim/site/pack/packer/opt/
Inside of ~/.config/nvim/lua/plugins.lua I added `use {"norcalli/nvim-colorizer.lua", opt = true}`
and `require_plugin("norcalli/nvim-colorizer.lua")`
~~~
I also tried:
~~~
git clone https://github.com/norcalli/nvim-colorizer.lua.git ~/.local/share/nvim/site/pack/packer/start/
Then `use "norcalli/nvim-colorizer.lua"` and `require_plugin("norcalli/nvim-colorizer.lua")`
inside of ~/.config/nvim/lua/plugins.lua
~~~
What I think might be the solution is adding a require line inside of `~/.config/nvim/init.lua`. I just have no idea what to call it.
I tried `require('colorizer')` and I also tried following your [blog](https://www.chrisatmachine.com/Neovim/10-adding-color/) with no luck.

**Comment by rebuilt** [comment]
After adding the 'use' line to plugins.lua did you run :PackerInstall and restart neovim?

**Comment by jtw023** [comment]
Oh I forgot to add that. For me, `:PackerClean`, `:PackerCompile`, and `:PackerInstall` aren't doing anything(presumably because everything is already installed). When I run :PackerStatus I do see the `nvim-colorizer.lua` package but when I open a file with hex codes there are no colors. Packer seems to be picking the extension up but not reading the right script that tells it what the extension does.
![2021-04-19_23-55](https://user-images.githubusercontent.com/59935328/115351169-d2318c80-a16a-11eb-9aa9-bb82a19bb259.png)

**Comment by rebuilt** [comment]
what is the content of nvim-colorizer.lua?

**Comment by rebuilt** [comment]
What is the content of your colorizer configuration?  

It should look something like
```bash
lua require'colorizer'.setup()
```

or 

```bash
require'colorizer'.setup(
  {'*';},
  {
    RGB      = true;         -- #RGB hex codes
    RRGGBB   = true;         -- #RRGGBB hex codes
    RRGGBBAA = true;         -- #RRGGBBAA hex codes
    rgb_fn   = true;         -- CSS rgb() and rgba() functions
    hsl_fn   = true;         -- CSS hsl() and hsla() functions
    css      = true;         -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
    css_fn   = true;         -- Enable all CSS *functions*: rgb_fn, hsl_fn
  })
```

**Comment by jtw023** [comment]
I believe I may have figured out the issue. Inside of `~/.config/nvim/lua/` there is no `lv-colorizer/` with an `init.lua` inside of it. Is that needed?
The nvim-colorizer.lua package that I cloned from github has a .git, .github, doc, license, lua, plugin, README, and test. If I go into the lua directory there is a `colorizer/` directory and a `colorizer.lua` [which is up on pastebin](https://pastebin.com/Bs3zSyAa). If I go into the colorizer directory there is an [nvim.lua](https://pastebin.com/LKUS3UUK) and a [trie.lua](https://pastebin.com/ZCefxK8i) both of which are also on pastebin.

As for the colorizer configuration, I tried the latter one in a file at ~/.config/nvim/lua/plug-colorizer.lua as he does on his blog but it didn't work. Where would I put the `lua require'colorizer'.setup()` line?

**Comment by rebuilt** [comment]
Just to diagnose the issue, place the following line at the bottom of your main init.lua.  Once you see it working you can move it to an external file.    ~/.config/nvim/lua/lv-colorizer/init.lua

```bash
require'colorizer'.setup()
```
If you were working in a .vim file you would need
```bash
lua require'colorizer'.setup()
```

**Comment by jtw023** [comment]
And it's working. I tried `require('colorizer')` when I first tried installing since that's the same form as all the rest in that init.lua file and it never even occured to me that I might have to do something different. `require 'colorizer'.setup()` was the answer. Thank you so much for your time!

Should I just close the issue or is there a solved button I should click first?

**Comment by rebuilt** [comment]
The command 
```bash
require'colorizer'.setup()
```
requires a module called 'colorizer' and calls the setup function.  The setup function loads the module and makes it available for you to use.  This is a standard way to start a plugin.  

Next time you install a plugin, you'll have to add your own configuration in the same way.  Packer does not write configuration files for you.  Technically, all your configuration could go in your main init.lua file but the file gets long.  Chris has made individual folders for each plugin because that is the recommended way to do it.  

From https://github.com/nanotee/nvim-lua-guide
```bash
Several Lua plugins might have identical filenames in their lua/ folder. This could lead to namespace clashes.

If two different plugins have a lua/main.lua file, then doing require('main') is ambiguous: which file do we want to source?

It might be a good idea to namespace your config or your plugin with a top-level folder, like so: lua/plugin_name/main.lua
```

**Comment by rebuilt** [comment]
You can just close the issue.  I'm not officially a part of this project.  I'm just trying to help out.

**Comment by jtw023** [comment]
Done! Thanks again for your help.

I also installed the [tagbar plugin](https://github.com/preservim/tagbar) which I think is a really cool adition for coding. 
If anyone wants to install this on arch linux, make sure to also run `sudo pacman -S ctags`. I had a bit of trouble figuring out that the arch linux version was only called `ctags` instead of `exuberant-ctags` like it is on debian-based distros and like the error shows when you first install the package. 

Anyways, if anyone sees this, I hope it helps!

**Comment by jonathan-raines** [comment]
I don't mean to resurrect the dead here, but I'm running into the same issue with vim-endwise. I have tried everything in this thread and I still can't seem to get the plugin to function. I was hoping for some guidance

**Comment by rebuilt** [comment]
Your ~.config/nvim/lua/plugins.lua file should have a line in it like
```bash
    use {"tpope/vim-endwise", opt = true}
```

If that doesn't help.  Create a new issue.  Describe the problem and what you've done so far.  Post the relevant lines from the relevant configuration files.
